---
root: true
extends:
  - eslint:recommended
  - standard
  - prettier
  - prettier/standard
  - plugin:eslint-comments/recommended
  - plugin:lodash/canonical
  - plugin:jest/recommended
  - plugin:jest/style
plugins:
  - "@typescript-eslint"
  - eslint-plugin-tsdoc
  - standard
  - prettier
  - eslint-comments
  - lodash
  - jest
  # TODO: import, node
overrides:
  - files: ["*.ts", "*.tsx"]
    extends:
      - "plugin:@typescript-eslint/eslint-recommended"
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@typescript-eslint/recommended"
  - files: ["*.spec.ts"]
    env:
      jest/globals: true
rules:
  prettier/prettier: error
  tsdoc/syntax: error
  lodash/chaining: [error, always]
env:
  node: true
parser: "@typescript-eslint/parser"
