---
root: true
extends:
  - eslint:recommended
  - standard
  - prettier
  - prettier/standard
  - plugin:jest/recommended
  - plugin:eslint-comments/recommended
plugins:
  - standard
  - prettier
  - eslint-comments
  # TODO: jest, import, node
rules:
  prettier/prettier: error
env:
  node: true
